apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: ${NAMESPACE}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ${REPO_NAME}
  namespace: ${NAMESPACE}
spec:
  targetNamespaces:
  - openshift-machine-api
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    opsrc-datastore: "true"
    opsrc-provider: redhat
  name: ${REPO_NAME}-registry
  namespace: ${NAMESPACE}
spec:
  displayName: ${REPO_NAME}
  icon:
    base64data: ""
    mediatype: ""
  image: ${REGISTRY_IMG}@${IMAGE_DIGEST}
  publisher: Red Hat
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ${REPO_NAME}
  namespace: ${NAMESPACE}
spec:
  channel: ${CHANNEL}
  name: ${REPO_NAME}
  source: ${REPO_NAME}-registry
  sourceNamespace: ${NAMESPACE}
